import type { Voice, VoiceCategory } from './types';

export const SEED_VOICES: Voice[] = [
  {
    id: 'seed-1',
    content: '2026年7月10号早上7点40左右出门上班去了，晚上8点45下班回到宿舍，发现自己的床铺被人坐了，还弄脏了。因为宿舍有一个夜班的女孩子，怀疑她早上下班，白天一天时间带了不是本宿舍人员进来，坐了我的床铺。因为这个女孩子睡我上铺，宿舍每个人都有一个凳子，我和她用同一张桌子，我的凳子每天都被我放衣服在上面，根本坐不了我的凳子，所以我怀疑在我去上班的时间段，不小心把我的床铺弄脏了，我心里很不舒服，因为在',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:10:00Z').toISOString(),
  },
  {
    id: 'seed-2',
    content: '2026年7月10号早上7点40左右出门上班去了，晚上8点45下班回到宿舍，发现自己的床铺被人坐了，还弄脏了。因为宿舍有一个夜班的女孩子，怀疑她早上下班，白天一天时间带了不是本宿舍人员进来，坐了我的床铺。因为这个女孩子睡我上铺，宿舍每个人都有一个凳子，我和她用同一张桌子，我的凳子每天都被我放衣服在上面，根本坐不了我的凳子，所以我怀疑在我去上班的时间段，不小心把我的床铺弄脏了，我心里很不舒服，因为在',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:11:00Z').toISOString(),
  },
  {
    id: 'seed-3',
    content: '宿舍灯坏了还有阳台的灯也不亮了',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:12:00Z').toISOString(),
  },
  {
    id: 'seed-4',
    content: '为什么都是整机打A  模组不配嘛',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:13:00Z').toISOString(),
  },
  {
    id: 'seed-5',
    content: '乱扣分，都没有告知我直接扣我5分绩效',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:14:00Z').toISOString(),
  },
  {
    id: 'seed-6',
    content: '请输出KPI结果明细。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:15:00Z').toISOString(),
  },
  {
    id: 'seed-7',
    content: '时间紧',
    category: 'attendance' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:16:00Z').toISOString(),
  },
  {
    id: 'seed-8',
    content: '时间紧',
    category: 'attendance' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:17:00Z').toISOString(),
  },
  {
    id: 'seed-9',
    content: '也不知道',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:18:00Z').toISOString(),
  },
  {
    id: 'seed-10',
    content: '按时上下班，佩戴好工衣工鞋工冒手套静电环不堆积等等不聊天不搭话，唉😔',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:19:00Z').toISOString(),
  },
  {
    id: 'seed-11',
    content: '绩效有什么问题？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:20:00Z').toISOString(),
  },
  {
    id: 'seed-12',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:21:00Z').toISOString(),
  },
  {
    id: 'seed-13',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:22:00Z').toISOString(),
  },
  {
    id: 'seed-14',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:23:00Z').toISOString(),
  },
  {
    id: 'seed-15',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:24:00Z').toISOString(),
  },
  {
    id: 'seed-16',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:25:00Z').toISOString(),
  },
  {
    id: 'seed-17',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:26:00Z').toISOString(),
  },
  {
    id: 'seed-18',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:27:00Z').toISOString(),
  },
  {
    id: 'seed-19',
    content: '补卡没补上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:28:00Z').toISOString(),
  },
  {
    id: 'seed-20',
    content: '物品有异常，下早班吗？我是包装部放纸箱',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:29:00Z').toISOString(),
  },
  {
    id: 'seed-21',
    content: '我在静音房上班，每次下班电脑我都关了，你要这样搞我也没法说',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:30:00Z').toISOString(),
  },
  {
    id: 'seed-22',
    content: '这是什么意思都不懂',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:31:00Z').toISOString(),
  },
  {
    id: 'seed-23',
    content: '我工作认真，没迟到没早退，为什么给我评B',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:32:00Z').toISOString(),
  },
  {
    id: 'seed-24',
    content: '宿舍空调不凉快，开十六度半夜还会被热醒，阳台的洗手台渗水，还有洗手台上方水管漏水',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:33:00Z').toISOString(),
  },
  {
    id: 'seed-25',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:34:00Z').toISOString(),
  },
  {
    id: 'seed-26',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:35:00Z').toISOString(),
  },
  {
    id: 'seed-27',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:36:00Z').toISOString(),
  },
  {
    id: 'seed-28',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:37:00Z').toISOString(),
  },
  {
    id: 'seed-29',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:38:00Z').toISOString(),
  },
  {
    id: 'seed-30',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:39:00Z').toISOString(),
  },
  {
    id: 'seed-31',
    content: '后阳台洗手台漏水，还有宿舍空调开16度也不怎么凉快，晚上经常热醒',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:40:00Z').toISOString(),
  },
  {
    id: 'seed-32',
    content: '打不上卡，或者打卡晚一分钟上不去卡，都不给补卡不给工时就让白干，说是厂里规定，这个规定违法的',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:41:00Z').toISOString(),
  },
  {
    id: 'seed-33',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:42:00Z').toISOString(),
  },
  {
    id: 'seed-34',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:43:00Z').toISOString(),
  },
  {
    id: 'seed-35',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:44:00Z').toISOString(),
  },
  {
    id: 'seed-36',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:45:00Z').toISOString(),
  },
  {
    id: 'seed-37',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:46:00Z').toISOString(),
  },
  {
    id: 'seed-38',
    content: '一期7栋317空调异响',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:47:00Z').toISOString(),
  },
  {
    id: 'seed-39',
    content: '空调早就不制冷了，修了一次还是没修好，16度就和没开一样，每天晚上睡觉都能被热醒早上起来全身是汗',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:48:00Z').toISOString(),
  },
  {
    id: 'seed-40',
    content: '中午在食堂买了一瓶水喝，还没喝两口，放在茶水间，下午准备去喝的时候已经被保洁阿姨扔掉了',
    category: 'other' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:49:00Z').toISOString(),
  },
  {
    id: 'seed-41',
    content: '中午在食堂买了一瓶水喝，还没喝两口，放在茶水间，下午准备去喝的时候已经被保洁阿姨扔掉了',
    category: 'other' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:50:00Z').toISOString(),
  },
  {
    id: 'seed-42',
    content: '中午在食堂买了一瓶水喝，还没喝两口，放在茶水间，下午准备去喝的时候已经被保洁阿姨扔掉了',
    category: 'other' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:51:00Z').toISOString(),
  },
  {
    id: 'seed-43',
    content: '中午在食堂买了一瓶水喝，还没喝两口，放在茶水间，下午准备去喝的时候已经被保洁阿姨扔掉了',
    category: 'other' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:52:00Z').toISOString(),
  },
  {
    id: 'seed-44',
    content: '试产车间21线，线长代永旺骂员工是傻逼',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:53:00Z').toISOString(),
  },
  {
    id: 'seed-45',
    content: '试产车间线长骂员工空调不开要热死员工',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:54:00Z').toISOString(),
  },
  {
    id: 'seed-46',
    content: '当时被调到3楼，第1次干那个活。然后我跟线长反馈说我跟不上前面那些人的节奏，让他给我换一个岗位试试看。然后他给我换了一个之后，就直接在群里面反馈我，并且扣我绩效分也没给我说。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:55:00Z').toISOString(),
  },
  {
    id: 'seed-47',
    content: '备注说明需修改',
    category: 'performance' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:56:00Z').toISOString(),
  },
  {
    id: 'seed-48',
    content: '我请假的是法定带薪年休假，为什么绩效给我打c呢？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:57:00Z').toISOString(),
  },
  {
    id: 'seed-49',
    content: '干了大半年了，还干很多个岗位，每个月都是B,新来的都能打A,意思我比他们差',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:58:00Z').toISOString(),
  },
  {
    id: 'seed-50',
    content: '怎么平绩效 绩效考核标准是什么',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:59:00Z').toISOString(),
  },
  {
    id: 'seed-51',
    content: '公司的公积金的基数能调高点吗，只能调个人的',
    category: 'other' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:10:00Z').toISOString(),
  },
  {
    id: 'seed-52',
    content: '没请假呀',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:11:00Z').toISOString(),
  },
  {
    id: 'seed-53',
    content: '是不是就不可以请假了吗，请假就打c了',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:12:00Z').toISOString(),
  },
  {
    id: 'seed-54',
    content: '新人第一天上班 直接削披风 没有任何培训 削不过来就压力',
    category: 'management' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:13:00Z').toISOString(),
  },
  {
    id: 'seed-55',
    content: '上个月我每次要补卡都加载不出来',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:14:00Z').toISOString(),
  },
  {
    id: 'seed-56',
    content: '不合理',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:15:00Z').toISOString(),
  },
  {
    id: 'seed-57',
    content: '只扣两分就被打c，原因是喇叭箱的分割壳提前拿出来，方便快速加工喇叭，',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:16:00Z').toISOString(),
  },
  {
    id: 'seed-58',
    content: '宿舍区附近很多蟑螂，请在每栋楼下组织消杀，谢谢',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:17:00Z').toISOString(),
  },
  {
    id: 'seed-59',
    content: '请假了四天',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:18:00Z').toISOString(),
  },
  {
    id: 'seed-60',
    content: '组长说下班因为原因是没有物料供不上来',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:19:00Z').toISOString(),
  },
  {
    id: 'seed-61',
    content: '空调不制冷 遥控器只能关 不能开',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:20:00Z').toISOString(),
  },
  {
    id: 'seed-62',
    content: '空调坏了',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:21:00Z').toISOString(),
  },
  {
    id: 'seed-63',
    content: '空调坏了',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:22:00Z').toISOString(),
  },
  {
    id: 'seed-64',
    content: '进门左手边的厕所抽风机声音很响，之前一直都没有这种情况，这两天声音可大',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:23:00Z').toISOString(),
  },
  {
    id: 'seed-65',
    content: '本人没犯错为啥绩效打C',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:24:00Z').toISOString(),
  },
  {
    id: 'seed-66',
    content: 'o3干o4的工作满三月不给升o4',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:25:00Z').toISOString(),
  },
  {
    id: 'seed-67',
    content: '管理问题从，我入职第二个月调工价的时候那个班长一直问我转不转正后面我说过两三个月再转正后面他说叫我三四个月以后找她，4月份的时候，我去找线长转正结果县长因为忙忘了后面5月10多号的样子，他给我拿了一张转正帮签一下直到后面那个班长一直针对我拿那个身体积分来扣我的积分到一个月以后，这个月评委c和这几天早上开会一直针对我我就不理解了整机班长何秀珍',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:26:00Z').toISOString(),
  },
  {
    id: 'seed-68',
    content: 'T108模组班长杨芊贞上班摸鱼经常去老化房地板上睡觉',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:27:00Z').toISOString(),
  },
  {
    id: 'seed-69',
    content: '1-413宿舍 有个一厂的大叔住在宿舍天天喝酒每天都打扰到我们休息 明天下班喝酒喝多了都发酒疯搁那跟我们吵架严重影响第二天上班',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:28:00Z').toISOString(),
  },
  {
    id: 'seed-70',
    content: '我是正式工T306线的，我咋没有绩效。当时我们线长给我放休，也没给我说请假的事，这是怎么回事？把我当傻子呀。发工资没有绩效！搞我呢。线长：李玲',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:29:00Z').toISOString(),
  },
  {
    id: 'seed-71',
    content: '男生寝室为什么会有女生来',
    category: 'housing' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:30:00Z').toISOString(),
  },
  {
    id: 'seed-72',
    content: '宿舍跳闸停电了，把闸推上去还是没电',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:31:00Z').toISOString(),
  },
  {
    id: 'seed-73',
    content: '二厂1—1025门口的垃圾都放半个月左右了，好大的味道，给我们的生活造成了困扰和不便，希望有关部门给予解决，谢谢！',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:32:00Z').toISOString(),
  },
  {
    id: 'seed-74',
    content: '？我为什么是c',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:33:00Z').toISOString(),
  },
  {
    id: 'seed-75',
    content: '我就一台电视机挡板没有贴放下去了，就一次也给我扣了三分，没有人不出错的，出一次错，也没有什么物料损失，为什么还扣我110.18块钱，有点不合理，人无完人，再说每个人都有犯错过',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:34:00Z').toISOString(),
  },
  {
    id: 'seed-76',
    content: '解除劳动合同不给当天结工资导致本人无法回家',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:35:00Z').toISOString(),
  },
  {
    id: 'seed-77',
    content: '1310寝室的灯不亮了',
    category: 'housing' as VoiceCategory,
    department: '其他部门',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:36:00Z').toISOString(),
  },
  {
    id: 'seed-78',
    content: '宿舍 WiFi 用不了了',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:37:00Z').toISOString(),
  },
  {
    id: 'seed-79',
    content: '绩效积分为什么是c',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:38:00Z').toISOString(),
  },
  {
    id: 'seed-80',
    content: '你好，宁秋荣不知道绩效为啥打C',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:39:00Z').toISOString(),
  },
  {
    id: 'seed-81',
    content: '你好，我不知道为什么打C',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:40:00Z').toISOString(),
  },
  {
    id: 'seed-82',
    content: '为什么女厕所会安排男保洁打扫，真的很吓人，年纪大也不能进女厕所啊',
    category: 'other' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:41:00Z').toISOString(),
  },
  {
    id: 'seed-83',
    content: '宿舍空调不制冷',
    category: 'housing' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:42:00Z').toISOString(),
  },
  {
    id: 'seed-84',
    content: '测试系统',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:43:00Z').toISOString(),
  },
  {
    id: 'seed-85',
    content: '四月份怎么整个75分？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:44:00Z').toISOString(),
  },
  {
    id: 'seed-86',
    content: '？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:45:00Z').toISOString(),
  },
  {
    id: 'seed-87',
    content: '我是一车间L13线的员工，4月27号因班长李国典误把别人违规，加到我考评里了，扣两分，下班发现以后及时联系班长，他知道弄错了，以撤回了考核，并向我道歉了，希望领导调查一下，',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:46:00Z').toISOString(),
  },
  {
    id: 'seed-88',
    content: '什么是绩效',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:47:00Z').toISOString(),
  },
  {
    id: 'seed-89',
    content: '为什么我的是c呢？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:48:00Z').toISOString(),
  },
  {
    id: 'seed-90',
    content: '卡时给你摆在这儿，咋是C，说个理由',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:49:00Z').toISOString(),
  },
  {
    id: 'seed-91',
    content: '你说我每次迟到或者早退你去调卡时',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:50:00Z').toISOString(),
  },
  {
    id: 'seed-92',
    content: '怎么就给我打70分？为啥？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:51:00Z').toISOString(),
  },
  {
    id: 'seed-93',
    content: '哪里有问题我迟到了吗？',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:52:00Z').toISOString(),
  },
  {
    id: 'seed-94',
    content: '能不能把你们的破考勤机调一下，漏打一次就算了几次是什么意思，又要天天搁着打卡还不把系统调好，光想着怎么赚员工钱是吧，还认同茂佳企业文化，拿什么认同？',
    category: 'attendance' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:53:00Z').toISOString(),
  },
  {
    id: 'seed-95',
    content: '一厂8一1211水管裂开',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:54:00Z').toISOString(),
  },
  {
    id: 'seed-96',
    content: '为什么给我打A？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:55:00Z').toISOString(),
  },
  {
    id: 'seed-97',
    content: '二期10栋宿舍10楼靠女生宿舍的饮水机漏水，热水小。按温开水键热水会一起出来，请处理',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:56:00Z').toISOString(),
  },
  {
    id: 'seed-98',
    content: '那是因为早上吃了饭堂的饭，因为饭堂的菜有很多菜都有辣椒，我有肠胃炎，吃辣的，喝豆浆油条都会拉肚子，我也经常吃药，吃了药好一点，过几天一吃辣的，喝豆浆，还是会拉肚子，就是有两三次我急着拉肚子肚子疼实在是憋不住了，管理员在后包装箱那里，我们离的距离有点远，我没来得及给他说，就急的差一点就拉裤子了没办法才跑厕所去了，请凉解，我保证不会有下次了。',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:57:00Z').toISOString(),
  },
  {
    id: 'seed-99',
    content: '那是因为早上吃了饭堂的饭，吃辣的，喝豆浆，我有肠胃炎，有两次急着拉肚子，管理人员在包装箱那里，你没有来得及说，就去了厕所，跑了慢一点就拉裤子了，换了谁都是一样的，希望领导理解一下。',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:58:00Z').toISOString(),
  },
  {
    id: 'seed-100',
    content: '周天下午五点四十五分，麻烦请安排增加班车，谢谢',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:59:00Z').toISOString(),
  },
  {
    id: 'seed-101',
    content: '希望星期天下午五点四十五分增加一趟班车，谢谢',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:10:00Z').toISOString(),
  },
  {
    id: 'seed-102',
    content: '家中有急事，需要离职。',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:11:00Z').toISOString(),
  },
  {
    id: 'seed-103',
    content: '打卡太严早了晚了都不行',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:12:00Z').toISOString(),
  },
  {
    id: 'seed-104',
    content: '公司比如说淡季计划不饱和的时候，产线有的时候8个小时，那就会面临晚上不加班（周一到周五）5点45下班没有班车到万信佳跟科技大厦，我们坐车一般都是到时尚公园下车，自己走路回去的（不管是大雨或暴雨）我们从来没有提过要求，现在班车进行优化，对线路进行了从新调整，对产线生产人员来说这样的线路调整一点都不合理，周一到周五晚上8点35分到万信佳的车本来15分钟就可以到，现在绕了一大圈，9点半能不能到家都是问题',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:13:00Z').toISOString(),
  },
  {
    id: 'seed-105',
    content: '公司比如说淡季计划不饱和的时候，产线有的时候8个小时，那就会面临晚上不加班（周一到周五）5点45下班没有班车到万信佳跟科技大厦，我们坐车一般都是到时尚公园下车，自己走路回去的（不管是大雨或暴雨）我们从来没有提过要求，现在班车进行优化，对线路进行了从新调整，对产线生产人员来说这样的线路调整一点都不合理，周一到周五晚上8点35分到万信佳的车本来15分钟就可以到，现在绕了一大圈，9点半能不能到家都是问题',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:14:00Z').toISOString(),
  },
  {
    id: 'seed-106',
    content: '公司比如说淡季计划不饱和的时候，产线有的时候8个小时，那就会面临晚上不加班（周一到周五）5点45下班没有班车到万信佳跟科技大厦，我们坐车一般都是到时尚公园下车，自己走路回去的（不管是大雨或暴雨）我们从来没有提过要求，现在班车进行优化，对线路进行了从新调整，对产线生产人员来说这样的线路调整一点都不合理，周一到周五晚上8点35分到万信佳的车本来15分钟就可以到，现在绕了一大圈，9点半能不能到家都是问题',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:15:00Z').toISOString(),
  },
  {
    id: 'seed-107',
    content: '公司比如说淡季计划不饱和的时候，产线有的时候8个小时，那就会面临晚上不加班（周一到周五）5点45下班没有班车到万信佳跟科技大厦，我们坐车一般都是到时尚公园下车，自己走路回去的（不管是大雨或暴雨）我们从来没有提过要求，现在班车进行优化，对线路进行了从新调整，对产线生产人员来说这样的线路调整一点都不合理，周一到周五晚上8点35分到万信佳的车本来15分钟就可以到，现在绕了一大圈，9点半能不能到家都是问题',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:16:00Z').toISOString(),
  },
  {
    id: 'seed-108',
    content: '公司比如说淡季计划不饱和的时候，产线有的时候8个小时，那就会面临晚上不加班（周一到周五）5点45下班没有班车到万信佳跟科技大厦，我们坐车一般都是到时尚公园下车，自己走路回去的（不管是大雨或暴雨）我们从来没有提过要求，现在班车进行优化，对线路进行了从新调整，对产线生产人员来说这样的线路调整一点都不合理，周一到周五晚上8点35分到万信佳的车本来15分钟就可以到，现在绕了一大圈，9点半能不能到家都是问题',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:17:00Z').toISOString(),
  },
  {
    id: 'seed-109',
    content: 'HY，你们好，我们公司是在进厂本月15号之前都是可以购买五险一金是吧，不是次月才购买。可是我3月11日进厂的，可我三月份都没帮买，能不能帮忙处理一下，因为小孩在潼侨上初中，中考在这里报名不了，必须三年不间断购买社保和三年居住证才能中考，所以三月份没买社保的话，上学会很麻烦，麻烦你们帮买一下',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:18:00Z').toISOString(),
  },
  {
    id: 'seed-110',
    content: '下半夜未到岗的并非是本人搞错名字了。可查看监控确认。',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:19:00Z').toISOString(),
  },
  {
    id: 'seed-111',
    content: '下半夜未到的并非是本人，搞错名字了可查看监控确认。',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:20:00Z').toISOString(),
  },
  {
    id: 'seed-112',
    content: '3-816',
    category: 'housing' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:21:00Z').toISOString(),
  },
  {
    id: 'seed-113',
    content: '公司帮弄的银行卡啥时候发',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:22:00Z').toISOString(),
  },
  {
    id: 'seed-114',
    content: '因工作流程繁多线上速度快',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:23:00Z').toISOString(),
  },
  {
    id: 'seed-115',
    content: '8楼电梯只能下不能上',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:24:00Z').toISOString(),
  },
  {
    id: 'seed-116',
    content: '。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:25:00Z').toISOString(),
  },
  {
    id: 'seed-117',
    content: '8号为啥是旷工🤔我当天下午才开始上班  不能改吗。。。',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:26:00Z').toISOString(),
  },
  {
    id: 'seed-118',
    content: '为什么给我少算了这么多工时明明是75.5',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:27:00Z').toISOString(),
  },
  {
    id: 'seed-119',
    content: '智能总装一厂生活区，健身房跑步机好多都是坏的用不了',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:28:00Z').toISOString(),
  },
  {
    id: 'seed-120',
    content: '1.卡机时，明明显示打卡成功，因为什么不显示时间表示没打上？？？',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:29:00Z').toISOString(),
  },
  {
    id: 'seed-121',
    content: '这个是因为当天晚上不加班下午下早班',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:30:00Z').toISOString(),
  },
  {
    id: 'seed-122',
    content: '我的绩效积分80，等级是C，岗位是滑封屏胶还连带放背板，产量一千七八都是我一个人在做，没有赶不上速度，已找线长解决绩效积分评价问题，线长回复是弄错了，我现申请绩效等级重新评价',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:31:00Z').toISOString(),
  },
  {
    id: 'seed-123',
    content: '初犯也不给机会，直接降级扣5分吗班长？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:32:00Z').toISOString(),
  },
  {
    id: 'seed-124',
    content: '为啥我朋友的分比我高，她明明被扣分了，',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:33:00Z').toISOString(),
  },
  {
    id: 'seed-125',
    content: '当时4点半左右没主板了，线长叫我们提前先去吃饭的',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:34:00Z').toISOString(),
  },
  {
    id: 'seed-126',
    content: '我不才扣12分吗🤔',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:35:00Z').toISOString(),
  },
  {
    id: 'seed-127',
    content: '提交申请离职中的信息',
    category: 'other' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:36:00Z').toISOString(),
  },
  {
    id: 'seed-128',
    content: '三月份看不到',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:37:00Z').toISOString(),
  },
  {
    id: 'seed-129',
    content: '我临时工绩效奖跟我有什么关系，就算有奖我也拿不到，那凭什么扣我钱呢',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:38:00Z').toISOString(),
  },
  {
    id: 'seed-130',
    content: '为什么绩效才80分，问题出在哪里，好像没犯过错',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:39:00Z').toISOString(),
  },
  {
    id: 'seed-131',
    content: '无昇议',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:40:00Z').toISOString(),
  },
  {
    id: 'seed-132',
    content: '有人每晚在2栋4楼打砸东西制造噪音，影响休息',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:41:00Z').toISOString(),
  },
  {
    id: 'seed-133',
    content: '有人每晚在4楼打砸东西制造噪音，影响休息',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:42:00Z').toISOString(),
  },
  {
    id: 'seed-134',
    content: 'B3栋一楼T311线旁洗手间，面向O类的质量红线（理念红线）标识漏了一个不字，不设计不良',
    category: 'other' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:43:00Z').toISOString(),
  },
  {
    id: 'seed-135',
    content: '花洒水量较小 洗脸池下方没有水管',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:44:00Z').toISOString(),
  },
  {
    id: 'seed-136',
    content: '洗澡间堵水,通过没有用',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:45:00Z').toISOString(),
  },
  {
    id: 'seed-137',
    content: '七楼的网络为什么这么差呀？能不能弄一下？而且宿舍大部分都是只有一个灯的，1-711的门还关不了先',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:46:00Z').toISOString(),
  },
  {
    id: 'seed-138',
    content: '室友晚上在宿舍里抽烟大声刷视频严重影响了我的身心健康与工作状态，多次沟通交流无效',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:47:00Z').toISOString(),
  },
  {
    id: 'seed-139',
    content: '离职问卷在哪里填写！我的考勤是对的',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:48:00Z').toISOString(),
  },
  {
    id: 'seed-140',
    content: '一车间T311线线长李佳豪作为一个线长，那权利欺压员工。满嘴胡说。',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:49:00Z').toISOString(),
  },
  {
    id: 'seed-141',
    content: '为啥请假这个会多出一个待审状态的？',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:50:00Z').toISOString(),
  },
  {
    id: 'seed-142',
    content: '36扣的是什么',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:51:00Z').toISOString(),
  },
  {
    id: 'seed-143',
    content: '10栋1-1331靠近厕所有镜子的下床已经四五个月没回来住却又一直占用着宿舍床位，宿舍也不打扫 厕所上到黑也不刷，以前就我们就两个的时候天天给我反锁在宿舍外面，跟她沟通过可以用钥匙在里面锁 我在外面用钥匙就可以开的，结果每次下早班了还是会被锁在门外一直敲门也没开 导致只能等到她八点起床才能回宿舍，如果她再次回来住不出意外也是会给我们反锁在宿舍外面，有时候回来宿舍也不锁门导致我们时不时会丢东西，并且',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:52:00Z').toISOString(),
  },
  {
    id: 'seed-144',
    content: '有考勤记录，离职厂区不结算工资',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:53:00Z').toISOString(),
  },
  {
    id: 'seed-145',
    content: '干了一天有没有工资',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:54:00Z').toISOString(),
  },
  {
    id: 'seed-146',
    content: '申述：当日中午11.01分打卡并非迟到，是班长朱水通知我们下班的。因为模组那边产品出不来而提前下班。当时线上的人都一起下班。后来看到这条消息，我还曾问过班长，她说这个不用管。请查证。',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:55:00Z').toISOString(),
  },
  {
    id: 'seed-147',
    content: '车间不要工人还不让吃饭！也不能出大门！',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:56:00Z').toISOString(),
  },
  {
    id: 'seed-148',
    content: '网络太卡了',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:57:00Z').toISOString(),
  },
  {
    id: 'seed-149',
    content: '网络卡的根本用不',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:58:00Z').toISOString(),
  },
  {
    id: 'seed-150',
    content: '提前打卡，现场管理员均以为按公司规定时间打卡为由不予补卡',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:59:00Z').toISOString(),
  },
  {
    id: 'seed-151',
    content: '为啥吃饭打不上卡？',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:10:00Z').toISOString(),
  },
  {
    id: 'seed-152',
    content: '为什么都加分了还是B',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:11:00Z').toISOString(),
  },
  {
    id: 'seed-153',
    content: '我陈春宁3月1号早上上班卡机没计录上，缺上班卡。3月3号8点上班，中午下班时线长让我下午别上班。我还了工服出去迟了。心情不号没打卡。12点的下班卡没打到，怎么现在连上班卡都不显示了。在那模组下班出来都漆黑的灯也没。我们新人都看不见卡机。没习惯。',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:12:00Z').toISOString(),
  },
  {
    id: 'seed-154',
    content: '30秒内没有压板。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:13:00Z').toISOString(),
  },
  {
    id: 'seed-155',
    content: '30秒内没有压板就被线长说了。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:14:00Z').toISOString(),
  },
  {
    id: 'seed-156',
    content: '流水线太快，，请求换刚位',
    category: 'management' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:15:00Z').toISOString(),
  },
  {
    id: 'seed-157',
    content: '与事实不符',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:16:00Z').toISOString(),
  },
  {
    id: 'seed-158',
    content: '不是加分了吗？为什么还是80？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:17:00Z').toISOString(),
  },
  {
    id: 'seed-159',
    content: '不是加分了吗？为什么还是80？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:18:00Z').toISOString(),
  },
  {
    id: 'seed-160',
    content: '不是加分了吗？为什么还是80？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:19:00Z').toISOString(),
  },
  {
    id: 'seed-161',
    content: '一直查询不到',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:20:00Z').toISOString(),
  },
  {
    id: 'seed-162',
    content: '说好的人走账清，现在不给工资',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:21:00Z').toISOString(),
  },
  {
    id: 'seed-163',
    content: '为什么扣20分',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:22:00Z').toISOString(),
  },
  {
    id: 'seed-164',
    content: '工资卡要求什么银行卡？',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:23:00Z').toISOString(),
  },
  {
    id: 'seed-165',
    content: '不知道补卡申请用来干嘛的，每次补卡都驳回原因是因为起草?那么请问什么样的理由才能算不潦草，又不规定规范?日期一过又补不了卡?现在离职前一天下班卡没打上找管理又说补不了？我还没离职怎么补不了，我没打上卡损失工资算我活该?那补打卡功能意义是什么',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:24:00Z').toISOString(),
  },
  {
    id: 'seed-166',
    content: '卡没有打上',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:25:00Z').toISOString(),
  },
  {
    id: 'seed-167',
    content: '2月20号还在年假，怎么显示旷工',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:26:00Z').toISOString(),
  },
  {
    id: 'seed-168',
    content: '厨师菜里少加点辣椒，少加点咸盐，让它自己做完了尝尝，',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:27:00Z').toISOString(),
  },
  {
    id: 'seed-169',
    content: '半夜一点多还有人走廊里乱窜，走廊灯光太亮，太密，一过人就亮',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:28:00Z').toISOString(),
  },
  {
    id: 'seed-170',
    content: '迟到2分钟都不行还扣分',
    category: 'management' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:29:00Z').toISOString(),
  },
  {
    id: 'seed-171',
    content: '我始终认为茂佳科技有限公司是一个无论在哪个方面都非常好的公司，无论是环境、餐饮、还是在平日的工作中，都能让员工们开开心心过好每一天……直到我们遇到了宿管殷宝林，其在为员工办理业务期间，态度属实恶劣，使用不当言论对员工进行辱骂，大呼小叫，显摆威严，一副高高在上的模样。最初我也认为是我做得不对，自身的问题，直到后面身边很多人都在谈论在他那办理业务时的遭遇。只要好好交流好好沟通，无论什么问题什么事都不是',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:30:00Z').toISOString(),
  },
  {
    id: 'seed-172',
    content: '宿管态度差，不能正常沟通说话处理事情还骂人，处理事情爱搭不理的。态度恶劣',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:31:00Z').toISOString(),
  },
  {
    id: 'seed-173',
    content: '宿舍办理人员殷宝林在员工办理入职时态度恶劣，说话大吼大叫，在入职办理完成后，骂了一句艹，后面一直在辱骂员工，让我感觉贵公司以后能否为我提供一个良好的环境',
    category: 'housing' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:32:00Z').toISOString(),
  },
  {
    id: 'seed-174',
    content: '请问一下办理离职手续不是驻厂的事务吗，怎么推来推去的，感觉就想踢皮球一样',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:33:00Z').toISOString(),
  },
  {
    id: 'seed-175',
    content: '被开的话会扣多少工资',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:34:00Z').toISOString(),
  },
  {
    id: 'seed-176',
    content: '一期T103产线无管理人员只有四个员工 不知道今天开不开线没有工作群也不知道去哪里询问',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:35:00Z').toISOString(),
  },
  {
    id: 'seed-177',
    content: '年假少了好几天，我也再问下2月14号那天我上了班的，是所有正式工都是调班扣年假吗？我的年假一共有10天现在手机打开一看，变成6天年假了',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:36:00Z').toISOString(),
  },
  {
    id: 'seed-178',
    content: '我想问一下，医疗保险在医院怎么用',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:37:00Z').toISOString(),
  },
  {
    id: 'seed-179',
    content: '没做到工期要扣600',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:38:00Z').toISOString(),
  },
  {
    id: 'seed-180',
    content: '说未满工期要扣六百',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:39:00Z').toISOString(),
  },
  {
    id: 'seed-181',
    content: '不知道为什么被扣费',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:40:00Z').toISOString(),
  },
  {
    id: 'seed-182',
    content: '辞职',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:41:00Z').toISOString(),
  },
  {
    id: 'seed-183',
    content: '补不了卡',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:42:00Z').toISOString(),
  },
  {
    id: 'seed-184',
    content: '8栋809花洒坏了',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:43:00Z').toISOString(),
  },
  {
    id: 'seed-185',
    content: '就是我的昨天工资条已经出来了。然后我希望今天11点之前把我的工资发给我，因为我等会马上坐车需要用钱，希望公司能处理',
    category: 'salary' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:44:00Z').toISOString(),
  },
  {
    id: 'seed-186',
    content: '101模组班长，每天混工时，凭什么，凭他是班长吗？如果员工这样你们会严肃处理，为什么他们不会，就因为他们是管理者吗？',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:45:00Z').toISOString(),
  },
  {
    id: 'seed-187',
    content: '2月4号晚上请的2月5号的病假 医院证明也拿给班长了 还是被记旷工',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:46:00Z').toISOString(),
  },
  {
    id: 'seed-188',
    content: '一直一直划赶一直一直划岗位，做不了',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:47:00Z').toISOString(),
  },
  {
    id: 'seed-189',
    content: '三楼米饭太硬了，菜品偏贵',
    category: 'dining' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:48:00Z').toISOString(),
  },
  {
    id: 'seed-190',
    content: '我要投诉B1车间L12线整机修理工和包装班班长！他们产线只要做商显机，他们就在包装屏外观岗位修理不良，喷漆！喷的那个漆的味道相当难闻，我们L11线装配段好几个人都被毒到！出现咳嗽，头晕！修理台是做摆设用的吗？',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:49:00Z').toISOString(),
  },
  {
    id: 'seed-191',
    content: '我要投诉B1车间L12线整机修理工和包装班班长！他们产线只要做商显机，他们就在包装屏外观岗位修理不良，喷漆！喷的那个漆的味道相当难闻，我们L11线装配段好几个人都被毒到！出现咳嗽，头晕！修理台是做摆设用的吗？',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:50:00Z').toISOString(),
  },
  {
    id: 'seed-192',
    content: '1-1331宿舍后阳台的洗手台上面的下水管漏水 已经持续了两天',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:51:00Z').toISOString(),
  },
  {
    id: 'seed-193',
    content: '三分扣得不明不白，本人有事先7点35线长微信说请假一天，线长没有回复',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:52:00Z').toISOString(),
  },
  {
    id: 'seed-194',
    content: '食堂打菜分量少',
    category: 'dining' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:53:00Z').toISOString(),
  },
  {
    id: 'seed-195',
    content: '我的考核77分为什么打c',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:54:00Z').toISOString(),
  },
  {
    id: 'seed-196',
    content: '11月13号8点半到九点前打出来的坏机由于没有位置放跟外面的扫条码岗位讲了暂时把坏机放在车架上，后面班长进来了，跟班长说明了一下情况，他并未理睬，请公平公正的纠正绩效错误',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:55:00Z').toISOString(),
  },
  {
    id: 'seed-197',
    content: '没有迟到、旷工、早退，也没做错事！为什么打的是C……',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:56:00Z').toISOString(),
  },
  {
    id: 'seed-198',
    content: '我上个什么没有干 也没有不开早会为什么打C',
    category: 'performance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:57:00Z').toISOString(),
  },
  {
    id: 'seed-199',
    content: '我的哪点做都不好？',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:58:00Z').toISOString(),
  },
  {
    id: 'seed-200',
    content: '就打一次处理报告就打C了一点不合理吧',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:59:00Z').toISOString(),
  },
  {
    id: 'seed-201',
    content: '绩效评分77，还给我打个C，越想越气，谁再管这个事儿。你人资管理证书是买的吧，我进了这么多年的厂，第一次遇到你这个坑货，明天不给我改过来，我天天发',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:10:00Z').toISOString(),
  },
  {
    id: 'seed-202',
    content: '还扣我钱，扣我分，现在还扣我绩效。如果我是半天都没有来，我可以接受。可我就晚了一个小时，打卡时间看不到嘛？为什么还给我打个C。',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:11:00Z').toISOString(),
  },
  {
    id: 'seed-203',
    content: '为什么给我评了个C？就因为我晚了一个小时嘛，你们的评分标准和绩效划分怎么操作的？',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:12:00Z').toISOString(),
  },
  {
    id: 'seed-204',
    content: '上月因回家有事，妹妹结婚，后因身体不适住院治疗，还是厂里有规定请假超多少天就评C',
    category: 'performance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:13:00Z').toISOString(),
  },
  {
    id: 'seed-205',
    content: '每次夜班都是一厂的先去一期餐厅吃饭每次我们都是最后吃到我们吃饭什么都没有了为什么不是他们最后吃',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:14:00Z').toISOString(),
  },
  {
    id: 'seed-206',
    content: '漏打卡',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:15:00Z').toISOString(),
  },
  {
    id: 'seed-207',
    content: '考勤方式过于严格，希望每个月有3次免费补卡次数',
    category: 'attendance' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:16:00Z').toISOString(),
  },
  {
    id: 'seed-208',
    content: '洗漱台破裂，需要维修！！！',
    category: 'housing' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:17:00Z').toISOString(),
  },
  {
    id: 'seed-209',
    content: '夜班转白班考勤异常',
    category: 'attendance' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:18:00Z').toISOString(),
  },
  {
    id: 'seed-210',
    content: '厂牌掉了，补办厂牌',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:19:00Z').toISOString(),
  },
  {
    id: 'seed-211',
    content: '9栋1106房间无线网络不可用。',
    category: 'housing' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:20:00Z').toISOString(),
  },
  {
    id: 'seed-212',
    content: 'B1栋 膜组车间 T104线班长 寇永军没有严格按照sop作业手法执行 导致员工用错物料 误导作业手法 出了问题点推卸责任给员工 态度极其恶劣 没有任何沟通能力  请公司严格及时速查',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:21:00Z').toISOString(),
  },
  {
    id: 'seed-213',
    content: 'B1栋 摸组车间T104线班长 寇永军 不严格按要求执行SOP作业 误导员工错用物料 乱交作业手法  态度极其恶劣 员工出错给不去正确解决措施方案 上前就是一通乱骂',
    category: 'management' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:22:00Z').toISOString(),
  },
  {
    id: 'seed-214',
    content: '沟通问题中（郭杰豪）领导辱骂员工',
    category: 'management' as VoiceCategory,
    department: '供应链',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:23:00Z').toISOString(),
  },
  {
    id: 'seed-215',
    content: '空调隔一两个小时就开始漏水',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:24:00Z').toISOString(),
  },
  {
    id: 'seed-216',
    content: '空调漏水，开一两个小时就开始漏水了',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:25:00Z').toISOString(),
  },
  {
    id: 'seed-217',
    content: '10-1-1324宿舍两个女生带两个男生进入女生宿舍',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:26:00Z').toISOString(),
  },
  {
    id: 'seed-218',
    content: '脚底板受伤，试产车间无创可贴，无碘伏，跟安全督察反馈过后，给我一顿输出说我事多，员工受伤难道不用创可贴吗？',
    category: 'other' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:27:00Z').toISOString(),
  },
  {
    id: 'seed-219',
    content: '住在一期宿舍，在总装二厂上班，上白班不能在一期食堂吃早餐，要到二期食堂，上夜班不能在一期食堂吃下午5点的晚餐。',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:28:00Z').toISOString(),
  },
  {
    id: 'seed-220',
    content: '8栋223宿舍厕所门坏了，开不了',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:29:00Z').toISOString(),
  },
  {
    id: 'seed-221',
    content: '刚才没有写全面，本人2025年9月28日星期日，卡五漏打卡，卡六的卡打到卡五了，希望各位领导重视，咱们厂监控可以调查，的确上班了，也一直不知道自己忘记打卡，直到9月29日凌晨2点多，看考勤才发现自己没有打卡，那天的工时本应该是11.5，现在是8，然后漏打卡也没有注红，就是写的个什么单次卡，很是麻烦了，希望看到帮忙我解决一下，不会有下次了，那我加班3小时半不可能就这样不管不顾了吧，谢谢',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:30:00Z').toISOString(),
  },
  {
    id: 'seed-222',
    content: '本人2025年9月28号，卡五漏打卡，卡六的卡打到卡五，的确上班了，是自己忘记打卡了，那么多监控，可以查啊，为什么就不能给我补卡啊，以后肯定不会发生同样的问题了',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:31:00Z').toISOString(),
  },
  {
    id: 'seed-223',
    content: '宿舍楼上漏水',
    category: 'housing' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:32:00Z').toISOString(),
  },
  {
    id: 'seed-224',
    content: '衣服被偷了',
    category: 'other' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:33:00Z').toISOString(),
  },
  {
    id: 'seed-225',
    content: '过道垃圾无人收拾',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:34:00Z').toISOString(),
  },
  {
    id: 'seed-226',
    content: '工资未发',
    category: 'salary' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:35:00Z').toISOString(),
  },
  {
    id: 'seed-227',
    content: '小饭堂建议改善',
    category: 'dining' as VoiceCategory,
    department: '注塑厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T18:36:00Z').toISOString(),
  },
  {
    id: 'seed-228',
    content: '无法补卡',
    category: 'attendance' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T19:37:00Z').toISOString(),
  },
  {
    id: 'seed-229',
    content: '超时加班',
    category: 'attendance' as VoiceCategory,
    department: '其他部门',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T08:38:00Z').toISOString(),
  },
  {
    id: 'seed-230',
    content: '线长组长动不动就（他妈的）这么说话',
    category: 'rough_management' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T09:39:00Z').toISOString(),
  },
  {
    id: 'seed-231',
    content: '一期3楼粉面窗口里面有头发',
    category: 'dining' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T10:40:00Z').toISOString(),
  },
  {
    id: 'seed-232',
    content: '10栋1031宿舍墙体漏',
    category: 'housing' as VoiceCategory,
    department: '智能总装二厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T11:41:00Z').toISOString(),
  },
  {
    id: 'seed-233',
    content: '9-406',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T12:42:00Z').toISOString(),
  },
  {
    id: 'seed-234',
    content: '9-406',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T13:43:00Z').toISOString(),
  },
  {
    id: 'seed-235',
    content: '一楼的自选快餐，称重不对，跑马称！瞎报价！',
    category: 'dining' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T14:44:00Z').toISOString(),
  },
  {
    id: 'seed-236',
    content: '9-406宿舍有个天天晚上喝酒，打呼噜相当厉害，影响我们三个！他自己都知道喝了酒打呼噜相当厉害还喝！故意影响我们！',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-11T15:45:00Z').toISOString(),
  },
  {
    id: 'seed-237',
    content: '宿舍就两个灯跟一台空调，为什么电费一个月能上到659度电，一个晚上能用22度电？',
    category: 'housing' as VoiceCategory,
    department: '智能总装一厂',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-12T16:46:00Z').toISOString(),
  },
  {
    id: 'seed-238',
    content: '空调无法制冷',
    category: 'housing' as VoiceCategory,
    department: '质量及运营中心',
    author: '',
    isAnonymous: true,
    likes: 0,
    aiReply: null,
    isBatch: true,
    createdAt: new Date('2026-07-10T17:47:00Z').toISOString(),
  }
];
